# Generated by Django 4.1 on 2022-09-07 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogPost',
            new_name='Log_post',
        ),
    ]
