# Generated by Django 4.1 on 2022-09-07 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0002_rename_logpost_log_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='Farm',
            new_name='farm',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='Produce',
            new_name='produce',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='scout_signature',
        ),
        migrations.AlterField(
            model_name='stack',
            name='scout_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stack',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stack', to='farm_map.zone'),
        ),
    ]
