# Generated by Django 4.1 on 2022-09-12 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0003_rename_farm_zone_farm_rename_produce_zone_produce_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_post',
            name='log_type',
        ),
        migrations.AlterField(
            model_name='log_post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stack',
            name='scout_week',
            field=models.IntegerField(choices=[(0, ''), (1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth')], default=0),
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='farm_map.stack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
