# Generated by Django 4.1 on 2022-09-19 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0005_stack_plant_date_alter_calibration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='plant_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='stack',
            name='scout_week',
            field=models.IntegerField(blank=True, choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth')], null=True),
        ),
    ]
