# Generated by Django 4.1 on 2022-09-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0006_alter_stack_plant_date_alter_stack_scout_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='light_schedule',
        ),
        migrations.AddField(
            model_name='produce',
            name='change_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produce',
            name='light_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produce',
            name='light_schedule_1',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produce',
            name='light_schedule_2',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zone',
            name='produce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone', to='farm_map.produce'),
        ),
    ]
