# Generated by Django 4.1 on 2022-09-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0007_remove_produce_light_schedule_produce_change_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='light_schedule_2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
