# Generated by Django 4.1 on 2022-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0008_alter_produce_light_schedule_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='light_on',
            field=models.BooleanField(default=False),
        ),
    ]
