# Generated by Django 4.1 on 2022-09-30 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0009_stack_light_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='automatic_lights',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Harvest_Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_forecast', to='farm_map.stack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecaster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
