# Generated by Django 4.1 on 2022-09-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0010_stack_automatic_lights_harvest_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='light_set_schedule',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second')], default=1),
        ),
    ]
