# Generated by Django 4.1 on 2022-09-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0011_stack_light_set_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest_forecast',
            name='dry_weight',
            field=models.FloatField(null=True),
        ),
    ]
