# Generated by Django 4.1 on 2022-11-02 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0012_harvest_forecast_dry_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suggestion', models.CharField(max_length=255)),
                ('restricted', models.BooleanField(default=True)),
                ('Working', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
