# Generated by Django 4.1 on 2022-11-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0013_change_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change_log',
            old_name='Suggestion',
            new_name='suggestion',
        ),
    ]
