# Generated by Django 4.1 on 2022-11-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0014_rename_suggestion_change_log_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_log',
            name='suggestion',
            field=models.TextField(max_length=255),
        ),
    ]
