# Generated by Django 4.1 on 2022-11-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0016_alter_change_log_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_log',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
