# Generated by Django 4.1 on 2022-11-03 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0017_change_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_log',
            name='votes',
            field=models.ManyToManyField(related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
