# Generated by Django 4.1 on 2023-01-11 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_map', '0018_change_log_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='change_log',
            name='down_votes',
            field=models.ManyToManyField(related_name='down_voter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='change_log',
            name='immolate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produce',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='species', to='farm_map.species'),
        ),
    ]
